{{- if (and .Values.ca .Values.ca.enabled .Values.ca.generate) }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: unikorn-ca
  namespace: {{ .Values.certManager.namespace }}
  labels:
    {{- include "unikorn.labels" . | nindent 4 }}
spec:
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: unikorn-self-signed-issuer
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 4096
  secretName: unikorn-ca
  isCA: true
  commonName: Unikorn CA
  duration: 87600h
{{- end }}
