apiVersion: v2
name: unikorn-core
description: A Helm chart for deploying Unikorn Core

type: application

# sentinel: patched at release time by release.yaml; overridden by --version for nightly builds
version: 0.0.0
appVersion: 0.0.0

icon: https://assets.unikorn-cloud.org/images/logos/dark-on-light/icon.svg

dependencies:
- name: unikorn-common
  version: 0.1.17
  repository: https://nscaledev.github.io/uni-helm-common
