openapi: 3.0.3
info:
  title: Common API types.
  version: 1.10.0
paths: {}
components:
  parameters:
    tagSelectorParameter:
      name: tag
      in: query
      description: |-
        A set of tags to match against resources in the form "name=value",
        thus when encoded you get "?tag=foo%3Dcat&bar%3Ddog".
      schema:
        type: array
        items:
          type: string
  schemas:
    error:
      description: Represents a structured error response returned by the API. It consolidates both OAuth 2.0-related and general API errors into a unified format.
      type: object
      required:
      - type
      - status
      - trace_id
      - error
      - error_description
      properties:
        type:
          description: Specifies whether the error originated from an OAuth 2.0 context or from the general API.
          type: string
          enum:
          - oauth2_error
          - api_error
        status:
          description: The HTTP status code returned with the response.
          type: integer
        trace_id:
          description: A unique identifier associated with the request, allowing the issue to be traced across internal systems. Clients can provide this value when contacting support to assist with debugging.
          type: string
        error:
          description: A concise, machine-readable identifier for the specific error, enabling clients to handle particular conditions programmatically.
          type: string
          enum:
          # Common error codes
          - invalid_request
          # OAuth 2.0 error codes
          - unsupported_grant_type
          - invalid_grant
          - invalid_token
          - invalid_client
          - access_denied
          - insufficient_scope
          - server_error
          # API error codes
          - token_expired
          - unauthorized
          - resource_missing
          - method_not_allowed
          - conflict
          - quota_exhausted
          - internal
        error_description:
          description: A human-readable explanation that provides additional context about the error. This field is omitted when no extra description is available.
          type: string
    kubernetesLabelValue:
      description: |-
        A valid Kubernetes label value, typically used for resource names that can be
        indexed in the database.
      type: string
      pattern: '^[0-9A-Za-z](?:[0-9A-Za-z-_.]{0,61}[0-9A-Za-z])?$'
    semver:
      description: |-
        A semantic version in the form v1.2.3.
        Pre-releases and variants are not currently supported.
      type: string
      pattern: '^v\d+\.\d+\.\d+$'
    tag:
      description: |-
        A tag mapping arbitrary names to values.  These have no special meaning
        for any component are are intended for use by end users to add additional
        context to a resource, for example to categorize it.
      type: object
      required:
      - name  
      - value 
      properties:
        name: 
          description: A unique tag name.
          type: string
        value:
          description: The value of the tag.
          type: string
    tagList:
      description: A list of tags.
      type: array
      items:    
        $ref: '#/components/schemas/tag'
    resourceMetadata:
      description: Metadata required for all API resource reads and writes.
      required:
      - name
      properties:
        name:
          $ref: '#/components/schemas/kubernetesLabelValue'
        description:
          description: |-
            The resource description, this optionally augments the name with more context.
          type: string
        tags:
          $ref: '#/components/schemas/tagList'
    staticResourceMetadata:
      description: |
        This metadata is for resources that just exist, and don't require
        any provisioning and health status, but benefit from a standardized
        metadata format.
      type: object
      allOf:
      - $ref: '#/components/schemas/resourceMetadata'
      - type: object
        required:
        - id
        - creationTime
        properties:
          id:
            description: The unique resource ID.
            type: string
          creationTime:
            description: The time the resource was created.
            type: string
            format: date-time
          createdBy:
            description: The user who created the resource.
            type: string
          modifiedTime:
            description: The time a resource was updated.
            type: string
            format: date-time
          modifiedBy:
            description: The user who updated the resource.
            type: string
    resourceProvisioningStatus:
      description: The provisioning state of a resource.
      type: string
      enum:
      - unknown
      - provisioning
      - provisioned
      - deprovisioning
      - error
    resourceHealthStatus:
      description: The health state of a resource.
      type: string
      enum:
      - unknown
      - healthy
      - degraded
      - error
    resourceReadMetadata:
      description: Metadata required by all resource reads.
      allOf:
      - $ref: '#/components/schemas/staticResourceMetadata'
      - type: object
        required:
        - provisioningStatus
        - healthStatus
        properties:
          deletionTime:
            description: The time the resource was deleted.
            type: string
            format: date-time
          provisioningStatus:
            $ref: '#/components/schemas/resourceProvisioningStatus'
          healthStatus:
            $ref: '#/components/schemas/resourceHealthStatus'
    organizationScopedResourceReadMetadata:
      description: Metadata required by organization scoped resource reads.
      allOf:
      - $ref: '#/components/schemas/resourceReadMetadata'
      - type: object
        required:
        - organizationId
        properties:
          organizationId:
            description: The organization identifier the resource belongs to.
            type: string
    projectScopedResourceReadMetadata:
      description: Metadata required by project scoped resource reads.
      allOf:
      - $ref: '#/components/schemas/organizationScopedResourceReadMetadata'
      - type: object
        required:
        - projectId
        properties:
          projectId:
            description: The project identifier the resource belongs to.
            type: string
    resourceWriteMetadata:
      $ref: '#/components/schemas/resourceMetadata'
  responses:
    acceptedResponse:
      description: |-
        The request has been accepted and will be fulfilled asynchronously.
        You may poll the resource and monitor its provisioning and health status
        to await completion of the operation.
    badRequestResponse:
      description: |-
        Request body failed schema validation, or the request does not contain
        all the required fields.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
          example:
            type: api_error
            status: 400
            trace_id: 77ce9d4485f746b6
            error: invalid_request
            error_description: The request is invalid and does not conform to the required schema.
    unauthorizedResponse:
      description: |-
        Authentication failed or the access token has expired.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
          example:
            type: api_error
            status: 401
            trace_id: 77ce9d4485f746b6
            error: token_expired
            error_description: The provided token has expired.
    forbiddenResponse:
      description: |-
        Request was denied by authorization, this may be caused by the authorization
        token not having the required scope for an API, or the user doesn't have the
        necessary privileges on the provider platform.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
          example:
            type: api_error
            status: 403
            trace_id: 77ce9d4485f746b6
            error: access_denied
            error_description: The operation was denied by the OpenID Connect provider.
    notFoundResponse:
      description: |-
        Unable to find a resource.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
          example:
            type: api_error
            status: 404
            trace_id: 77ce9d4485f746b6
            error: resource_missing
            error_description: The requested resource was not found.
    conflictResponse:
      description: |-
        Resource conflicts with another, usually this means they have the same name.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
          example:
            type: api_error
            status: 409
            trace_id: 77ce9d4485f746b6
            error: conflict
            error_description: The resource is being deleted and cannot be modified.
    internalServerErrorResponse:
      description: |-
        An unexpected or unhandled error occurred. This may be a transient error and
        may succeed on a retry.  If this isn't the case, please report it as an issue.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
          example:
            type: api_error
            status: 500
            trace_id: 77ce9d4485f746b6
            error: internal
            error_description: The server encountered an unexpected condition. Please try again later. If the problem persists, please contact our team.
