// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xZYW/kxs3+K4TeBHmL7q19d0CALhAEbq5tDk0R4+KmaLPugqvhSpNIHN3MyD7l4P9e",
	"kCPtane1tnN2v/XD4byaEYd8SD5DUh+z3NWNY+IYssXHrEGPNUXy+iti8QNVlEfnL4cFeW4o5N420TrO",
	"FtkFBIrgNhCxCBAd1BjzErBAyyGCp+Ban1MAyxBLgo3zNSwzxpq+usGqpWU2W3Is2wC3JTEQ586Qgc61",
	"UFCEZfZ1xOKrjXOfv36TY1y25+evvpRHa/Sfv35jXLHM5tkss6LN+5Z8l81UfLYQE7JZFvKSahTVbaQ6",
	"2dY1sh6it1xkd7PhAXqPXXZ3dzfLPIXGcSDdj3lOTSTzrn94jMNVSeDpfUshQokB1kQMw2uAbODWVhWs",
	"CTZttbFVJU9Dx3npHbs2VN18yf90LdTYQeOqStEa4FMBtWMbnQcbAzTe3dhgHVsudLEkrGIJIWJsw5Kj",
	"A7xFG0E8XJEoqU4qCVxDHuXBXAxfo3mX1B7bljuOxFFNb5rK5vrC2c9BbP2Y0QcUqfqn985ni8zyDVbW",
	"rHoMsllaWe2jNCC0dqaD/hXRYueizzxtskX2f2e70DxLq+EsnaXe2Rf7bix2g1bATS+BHqHaz8D5HtS0",
	"2zgKwE4w4oiWl4xb2N+31pOBjaXKBAUqd7ypbP5EmAYpJ/DBncdvbSxVmYA1gQQ0YOUJTQf0wYYYngW3",
	"/rBBrZCORXaxJD+DNrRYVR3E0gaoCTmISh2UeEP7yilGG+fX1hjip4G0FXMCpTaQh9yTIY4WqwDGqR+3",
	"Wm3913h7YysqKDxjlN1iAENsycC6A2xj6bz9tY+xhBR2kuk5tiFtEqX2NkqG/kI8qC1ZvKd4yF2jZAnI",
	"cHH5dhu8artELn+xM3jJTDmFgL4bmQwuUa5yhSEPTYVR+Fd9ZTmSZ6x+IH9D/k9i9NO8FlTQKv2cdlyf",
	"mtFBsj6v0NbP4JkLhpbpQ0O5kK3z0HKJbOQsfQdcnrfek5nD1cg/CNEjB0sc+33IZsmyGto8J5HFIDkZ",
	"fTcHeLtJ7rUKvkCbY6AZNBVhEOc1zkewETCI22wIbcoLdvHPrmXzNIDZxdVGxJxAd8RtZHZEsqU5pY1n",
	"QPvvjOuKxIsbywZ2nKW2uobYmkvvonpjoJhPM30vZ1YpwkK2+CkrY2wWZ2eyPse8pnnu6uxab209Llvo",
	"lrA4OyM2jbMcd/seDcEJW6ZA+b4hfvtGidQWbbpgQdM/OjA25O6GvHKAkFayGHqDUuVT2hgtF0tGydh0",
	"ImyVhxS5Nkg0tp77NJIYrDSAVQbyIc2kuLZBC6tWcl7YxSUaz5F3upXuVkSOVEwObXkQSU8MYCmHQlgl",
	"7jx1A+4jlBjjOShiSu5AqkmxnpSkeqMPjdBwb3/jnbLruqJvktFPw2FP4mp4/8GkTuWN3D59LX3rHRda",
	"UeNz5PXV7q4w2zPluNBxxFywk1ogd95THmHdJg6UOt+3ucIqu9uBHpa8VoFiKRkwrXJGoBrFD4lxpbba",
	"ah6OUj5dTt8Jbx1V3PJUatq9F7YpFUuMGt+FR447D++V1do3DD3B0ZUyJfiLkArLVJGXLsRU/Mweailm",
	"g/cPD/oLMfkBDqglKgqaad2O0QqSWpI50eaVHNR4qeCjTZ3JCakXIG0c9VKTUhLVyEb+6iuDb6+uLvst",
	"0nXNQcuAAOgJ1hjS/Scbv5f0gVfz81cQGsrtpo/ymUaBbE+yySRtRUdvKUpBkloSPSBoRXNx+TaAFpji",
	"JTnABRrkpnppd55YTNzWQvrHPcZBzXFIMOMbc1R51xRLZ1ayilXlbnVvy6Ft5AIns6rJWFypA2dDz7IS",
	"9ojdKjq3qtAXlM1OJvKugL2eCIyJND9034/k1wJKHw6QVtdDmagSJoLuLmkr1CV4nS7Fdmq59c+UK3v8",
	"0q7JM0UK3+Gaqh+lOZ8KLPUB/HW7GyrZDtrMzyB2Tc8TevmJv7eViKTKKDPXtGTLhj6QGRjNYEQJPI1z",
	"jFKhZovs3z+dv/jDxYt/4Ytfr///68Xu14vV/Prj+ezLl3ejHb/7+rOpdDx1lx9Z2N/kOHFTby/Lbv+i",
	"P07LE4XL/cx8ivruxnXNx2nW7uuFYd+jeeogZLbnzE6YMBU5zhfIg9rSuIyqPjR/o4jiV4Wlqr7fZIuf",
	"7sfBT719N/t4gPH42LdmGpnxHrDaMG4s+f3hypoqxzq9ehigg0OP4bg+vFYHC3bN3brb10ubvVHFLl1+",
	"Gjo03onU5wD1kU46hrnX4RTC/fKzgLs76lNxHbQ5Denw6FsdmP2gl9O0ZaORGmmhsVc3DJdSy7+wu+Vs",
	"lqX9XSaKFh7NrsadvAYGYWNXPmShDgSqSq7QA9vSiNHbSOGYje69a67G3hot9bMMpz+U0bEtaokpdbBO",
	"pPSyr53XCVKkD3GyEkrT2PvDc/L2kSoKiwd5M2KRePIgnPTc6xHUl6Op6X2e35uuPtr/47fGPzUODB0s",
	"PxwYn5bnoq7N3x0G13FeG0pz4Stbn7hWoq1pP5nT6KuiKL2R1jnSeiwyg5FeyPYp95cHmfYY6t/Lzrt9",
	"bH+bpAmfT9DO4ZYDrT+VjiRX7+Ggf0i+/i///+v5H6i+OfXxqu9GpbjRGmH0merm5fzV/PV8yZeeXnjS",
	"KV8C+ga9RUFCWh/9hNB6TxyrDrZdxEENe7Ncmt8vl/PRf5N16on8/c3F0z2Zn3vCSOaP3XQw6Ij5tnTQ",
	"7ztqmY901o2fQCX9AY+nEnuiCGnZvm9Hwt++mdSzdkZbzActbxvzOMsHiQ9Yjvt29+Ifa/dBWFttZ8eQ",
	"P4Ke0tx7IBQb9jqzvin7uQ39lHimUW4cfxEH8lkycvfAd8c0DlgT08ZG2HhXA8oSG/TG/kpmyVsVkuHz",
	"JWcTHUXEYnKmgQXU2DR6uF/b6NF3Q1vpUgsadFRKgdLXEXZpsoCVfr/SAWv6rNLBNns0jeWflQ7e9ETb",
	"BhIOJzYaGHoEGiP/bOLEJfe0p0tbOGf6ej/4k6UcIxU6QQUbj+l54MdDc/uoFqtPTpluptt0iTxdGr76",
	"Riwerr9VkUHm9bRfpodxF1D14zgh7L252gPMPf313fLG6Yd6GytZ+sbVtdMvYSCb9YSesrNF9nL+8vX8",
	"fOjysbHZIns9P5+/ThRcih53d/8JAAD//xDNRQTvIAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
