// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xZbW/cxvH/KgP+E+Rf9HSWY8dpDggCN24RoSki2G6LNucehtwhuQm5S+/DSYyh717M",
	"LHnH01EnxY77qi8M68jl7sxvZn7zsO+ywradNWSCz1bvsg4dthTIya+A1StqqAjWXY4v+LkiXzjdBW1N",
	"tsqeg6cAtoSAlYdgocVQ1IAVauMDOPI2uoI8aAOhJiita2GdGWzp6y02kdbZYm1CHT1c1WSATGEVKeht",
	"hIoCrLNvAlZfl9Z++uRFgWEdz88/f5aj+/TJC2WrdbbMFplmSd5Gcn22kK2zFYufLTJf1NQii60DtUmv",
	"vuP3PjhtquxmMT5A57DPbm5uFpkj31njSdZjUVAXSL0cHh5j8LomcPQ2kg9Qo4ecyMD4GaBRcKWbBnKC",
	"Mjalbhp+6ntT1M4aG33TL9fmnzZCiz10tmkEqRE62aC1RgfrQAcPnbNb7bU12lTysiZsQg0+YIh+bYIF",
	"vEIdgK3bEAspBqoJbEcO+cGSFc9RvUxiT3UrrAlkgqjedY0u5INHP3nW9V1G18i7yp/OWZetMm222Gi1",
	"GTDIFunN5m6UNPuDfCQKKEsejGWJjThIsAMEb6N2pCCZkU2dlMxWT8/PF1lwWNBGq2yVffllQV+pp0//",
	"8EX55dNn+TPWb2/8TxyV2Sr7v0d7h3+U3vpHSQux+6HAAzaQW9VDibrZCQIiuuCyAOt2svLqqS4BtVkb",
	"3Bl00KbU1CgvJmCFG118oAHGXU4iP3iTZv9kz1HU0OifBRoWOSdordKlJnWI9VcfH+tBvFEVD1c61IDG",
	"hprcAqKP2DQ9hFp7aAmNZ0x7qHFLgq7HloBjX3Atrcu1UmQ+DFgOYu83iowmdQLdXVzBFXpIyyHvRbAf",
	"OjIXL+BbawwVIUWvIncI8JP/ljMfyocx1NbpXwZXTuBiz45QYPR7JQ4WMsX8TEa8vMYtO9OtaLWdMD2g",
	"geeXF7sYiZ6cBIj5LOwst2ZcyHt0PXROb3VDFXmwKV+McEHXYGBuEPNqE8gZbF6R25L7Eyv9oRSWNjxh",
	"Yy9nSYKKvFpCB6Kh644KDqTCGqWFXOGyIfQEwfUpE0KDgdwSLspRqbyhFjpyXvvgF9ClD4QzigA2OgiE",
	"7dRJvvj4jPf8QB/rIJoajWLik2/AFkV0jtQSXk9cBSE4NF6TCcM6NGpt+K2PRUG8lwEER8H1S0gocAoQ",
	"P2BACvS0A8FRZ10AHQA9Q6y9jymqjQ1/ttGoD7P1SIWbVnvPNcC9+YrUnj85gNjxSxbkMIiffmz7/M1g",
	"3hBnx1IbJYgmqQSdaMYopQ9ESMJ7Q9cdh/MJeIbgVJD4gGuf4aNDYB5/dMeNoSYTBtXGZD2wTiLxORlv",
	"dif7ifrvjqizc+RZEEDwwcUiRLcLibFWZO+Ozuwp8/nlxRIupA7wVsoF8pDbUMMPLC58vjw/c8TEkHJw",
	"RYYcNvxd2pprJK7lIBpJyVI7Y2BoO8cZJ2g6JfdzPrrQHFktFrU2dOYIlbiQVgxXqckJT0sC7ajQpS7S",
	"4Qsgdjbm9qLRonywkNgAOnRBF7FBtyc9qUsrh22LbIem6VlQMrHNVj/OlIjR+NhxoJPaVA5N2Egdvtgt",
	"lYeT32K/ye8kVrY4StLa+FiWuuDXG8lF7IzC3psE1eLIw6exky3mKKKlUFu1MTZssGnslaybFF5vow24",
	"oesaIxNGtk9S2ZvFcdMxE1LH9qtji2ZvNLruGjTJxUONu1rCA6pkBGwkhdB1AMxtTOQqRw2MLaUn14C2",
	"1YE9T5ouY4Gug0OYCMCLcIu64aPZlEcqjPE91w599/r15dCQADd0++iQsm7obyRwJnszYhU5acp2fHEM",
	"SzT6bTzwYfTeFlpCabK/uNoCxFxjkSLJhF055/SMBQdf4ayXYBNzge8994pL+HZw/ALNCHVKXNK4JuiG",
	"jM3bD/7Mm6PnvJ5kUZTHqtKmmgFRes1UNXGUDIhOtB8cZZaD925l85+oCAzbzzEnZyiQ/x5zav7Ogs5B",
	"mHqvv+xWQ8PLk2ILCH2XQhikBiwTzaX8xyW2T+7HuOS0NtoouiY1tvgKA+aYDNthYFSzVfbvH8/Pvnp+",
	"9i88++XN/3+z2v862yzfvDtfPHt8M1nxu28+mXM56yo0QxX6iiNbjY3DS0L1VwrIh0uma5ofymz14+mE",
	"4ua+vlm8u0Ww02Mv1LzHT9dMXfOglc+psUbmJPc7w61Dj6395nYWHDXYV+J5fyiXsOGkmGFqSY1o5yzv",
	"+luA+kAjHcM8yHAXwsPr3wTc/VHvi+sozd2Qjo++k/HMqxNsORngENjyoLDb59Bofjb2ilNgWt9nLGjl",
	"UO2LtNlcM242NeV9Gkr31qRq5FC3NNByOpA/LkVOJrSDOcTk1dB42i6lsIb70qpNNUedGCdRaWsdjQlu",
	"NiWl2d9p95ylSM44WPn7vg1Yfa99OHInOffNBOrLyYzulOUPZnkPtv/0q+lP8QNFt17f7xjvF+csri5e",
	"3nau47iWSZO25rVu75ieBt3SYTCnOYVMqBiDVPpmq4zL6DNePmf++lakPYT6D6Lz5hDbX7fTjM1naOf2",
	"kltSvy8dcaye4KB/cLz+L/4/evx7ard3XZO0yB0qbMl5qREmFyLbx8vPl0+Wa3PpuEmTOUgCeotOo7Se",
	"jtJYOTpHJjQ97PqnW4XWdr1Wv1+vl5P/Prmrfp+J319dPJ2I/MIRF+V/7OedQeaBV7WFYd0BBcwaWBa+",
	"B5UMBzycSvQdRcjQe+w2v3gxK+c4Rr9X89iph2k+7niP5nio97D9Q/W+5dbSgBxA/gB6SpPBkVC455y0",
	"D0Pn8FP0AehaS3smF0DmszCSz9qg6e+55VpAHgPkZKjUAUpnW5nNoFHoFDfxa7MTYRibrE020zAFrOai",
	"NWAFLXadHO5yHRy6fux9bOqT/BLgdU2e0ijb2DRCwUbuJ7Sp1ibNwHvYRY+EMf/jbtOogWijJ+ZwMkoc",
	"Q45ApSZt/dqMfb1MhEY4F/L5MMHjVwUGqmSMAXpmUjTy4x0dNWudrlBmHHA730uy56V+eLhjDPiATlcE",
	"Gfd8M28XYdoZYRturYcbZ7n9HW9272Hu+btebUor18I6NPzqW9u2Vq4tuA1OOW6g7GyVPV4+Pl+eSyva",
	"kcFOZ6vsyfJ8+SRRcM1y3Nz8JwAA//8S+A1eWR8AAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
