// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xZ4Y7byA1+FUK9w7Wo19kkwAE1cDhse20v6BW3SLZXtNHWoDW0NYnEUWZG3nUCv3tB",
	"jmTLXnl3L9n+648ga82IQ34kP5KjT1nh6sYxcQzZ7FPWoMeaInn9FXH1hioqovOX/YI8NxQKb5toHWez",
	"7AICRXBLiLgKEB3UGIsScIWWQwRPwbW+oACWIZYES+dryDPGmr5bY9VSnk1yjmUb4KYkBuLCGTKwcS2s",
	"KEKefR9x9d3Sua9f/lBgzNvz8xffLtB//fIH41Z5Ns0mmRVNPrTkN9lERWczUT+bZKEoqUZR20aqk12b",
	"RtZD9JZX2XbSP0DvcZNtt9tJ5ik0jgPpfiwKaiKZ193DuxhclQSePrQUIpQYYEHE0L8GyAZubFXBgmDZ",
	"VktbVfI0bLgovWPXhmozzflfroUaN9C4qlKkeuhUQO3YRufBxgCNd2sbrGPLK10sCatYQogY25BzdIA3",
	"aCOIdysSJdVBJYFryKM8mIrhCzSvk9pD2wrHkTiq6U1T2UJfePYuiK2fMrpFkap/eu98Nsssr7GyZt5h",
	"kE3SyvwQpR6hhTMb6F4RLfYu+srTMptlv3m2D8tnaTU8S2epdw7Fvh6KXaIVcNNLoEeo9hNwvgM17TaO",
	"ArATjDii5ZxxB/uH1noysLRUmaBAFY6XlS2+EKZeygl8cO/xGxtLVSZgTSABDVh5QrMBurUhhifBrTus",
	"VyukY5FdLMlPoA0tVtUGYmkD1IQcRKUNlLimQ+UUo6XzC2sM8ZeBtBNzAqU2kIfCkyGOFqsAxqkfd1rt",
	"/Nd4u7YVrSg8YZTdYABDbMnAYgPYxtJ5+7GLsYQUbiTTC2xD2iRKHWyUDH1P3KstWXygeChco0QJyHBx",
	"+WoXvGq7RC5/szc4Z6aCQkC/GZgMLtGtcoUhD02FUbhXfWU5kmes3pBfk/+zGP1lXgsqaJ5+jjuuS83o",
	"IFlfVGjrJ/DMBUPLdNtQIWTrPLRcIhs5S98BVxSt92SmcDXwD0L0yMESx24fsslZVkNbFCSyGCQno99M",
	"AV4tk3utgi/QFhhoAk1FGMR5jfMRbAQM4jYbQpvygl38i2vZfBnA7OJ8KWJOoDvgNjJ7ItnRnNLGE6D9",
	"D8ZFReLFpWUDe85SW1vuA52+0F6pniHMU6qdIsw2lsICSVrH/U8RUWNy+xxMinUxLMWebhvJ2mm23Z0c",
	"BpYc9wp/JSZviy7makncFU20VGO0gq2ysBPjXkhv03gp2tHSfVIvQLo26qSm1kY0QzbyV0cGP15dXXZb",
	"pMmagmZ+APQECwwp5GXjzwIBvJiev4DQUGGXHRYTWLRRtyfZZJK2oqO3FIWDUheiBwQlsYvLVwG0pkAs",
	"UQ5wgXq5iSL354nFxG2dzd6OtBVHNHMcJMMkGRTbmmLpzFxWsarcje5tObSN5CyZeU3G4lzbwEnfpswl",
	"AuJmHp2bV+hXsrSvTdeTu23kSIgeu+kX8gsxvnM7pNVFXwFUgiBwJHubtJIwE1xOs+xeLbd4R4Um/Pt2",
	"QZ4pUvgJF1T9Ij33WAAp1vC33W6oZDtojz6BuGlsoe2AljXx645kpAWQ3gAjFMiwoJwtG7ol0zf9BiNK",
	"gGk8Y5Tik82y/7w9P/vDxdm/8ezj9W+/n+1/nc2n15/OJ98+3w52/O77r7IR1J1fIXeF9Y0UTtM3Nq8J",
	"zd8pohyuzFNVPy+z2dv7WcGPvb2dfDrKw+Gxr8z4SDDcA1YblqUlf9jcL6hyrJPTw44/OvSut6+Pqay3",
	"YN9cLDaHemmzMagY0mWmprfxTqQ+BaiPdNJdmDsdTiHcLT8JuPujPhfXXpvTkPaPftSB7Y0y5bhlg5GO",
	"ZHgbFto9Q7b8nt2NtMppv4y/hlYezb5ojnJVL2zoyocs1Ia0qoTPj2xLI663kcLdinUvIV4NvTVY6npp",
	"pz+UdrBd1RJT6mCdiLTy1M7rBBPpNk7H+CHdBtwfnqMUuZ1kEVfhoXcjrn7S1uoonPTc6wHUl4Op/T7P",
	"H0z3j/b/8K3hT40DQ0fLDwfG5+W5qGuL18fBdTevDaV7iStbn7hPibamw2ROo1dFUZotLcY1xmyWGYx0",
	"JtvH3F8eZdpjqP8gO7eH2P46SSM+H6Gd4y1HWn8uHUmu3sNB/5R8/X/+/8/zP1C9PnVxWqOMGbAmH7RH",
	"GFyRrp9PX0xfTnO+9HTmSafMBPQavUVBQvpwvcKS8ZZjJZNr19IeNVrrPDe/z/Pp4L/RZupE/v7q5ume",
	"zC88YSTzx814MOgVx03poNt3QAGjDtaNn0El3QGPpxJ7oglp2X5oB8Jf/TCqZ+2MzjsPWt425nGW9xIf",
	"sBwP7e7EP9buo7C2OlsNIX8EPaV7l55QbDgYH7rJ4V0buluKiUa5cfxN7MknZ+TNA/feaTZdENPSRlh6",
	"VwPKEhv0xn4kk/NOhWT4NOdsZGCKuBodsHEFNTaNHu4XNnqZdrvZx6U5KUwBrkoKlG7n2KUxFyu9P7W8",
	"yjld621glz2axvLPciQdqWVLG0g4nNhoYOgRaIz8s4kTc+5oT5d2cE709e5GRZYKjLTSKxmw8S499/x4",
	"bG4X1WJ1uuIdCcD1+CwpkadL/VeHiKuH+29VpJd5Pe4XZdoRZSsbdt+g9HtQ/63nAeYe//pjeen0Q5GN",
	"lSz9ydW105tYGYNTjesoO5tlz6fPn0/PdRRtiLGx2Sx7OT2fvkwUXIoe2+1/AwAA///K6C3KaxsAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
