// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package openapi

import (
	"time"
)

// Defines values for ErrorError.
const (
	AccessDenied         ErrorError = "access_denied"
	Conflict             ErrorError = "conflict"
	InsufficientScope    ErrorError = "insufficient_scope"
	Internal             ErrorError = "internal"
	InvalidClient        ErrorError = "invalid_client"
	InvalidGrant         ErrorError = "invalid_grant"
	InvalidRequest       ErrorError = "invalid_request"
	InvalidToken         ErrorError = "invalid_token"
	MethodNotAllowed     ErrorError = "method_not_allowed"
	QuotaExhausted       ErrorError = "quota_exhausted"
	ResourceMissing      ErrorError = "resource_missing"
	ServerError          ErrorError = "server_error"
	TokenExpired         ErrorError = "token_expired"
	Unauthorized         ErrorError = "unauthorized"
	UnsupportedGrantType ErrorError = "unsupported_grant_type"
)

// Defines values for ErrorType.
const (
	ApiError    ErrorType = "api_error"
	Oauth2Error ErrorType = "oauth2_error"
)

// Defines values for ResourceHealthStatus.
const (
	ResourceHealthStatusDegraded ResourceHealthStatus = "degraded"
	ResourceHealthStatusError    ResourceHealthStatus = "error"
	ResourceHealthStatusHealthy  ResourceHealthStatus = "healthy"
	ResourceHealthStatusUnknown  ResourceHealthStatus = "unknown"
)

// Defines values for ResourceProvisioningStatus.
const (
	ResourceProvisioningStatusDeprovisioning ResourceProvisioningStatus = "deprovisioning"
	ResourceProvisioningStatusError          ResourceProvisioningStatus = "error"
	ResourceProvisioningStatusProvisioned    ResourceProvisioningStatus = "provisioned"
	ResourceProvisioningStatusProvisioning   ResourceProvisioningStatus = "provisioning"
	ResourceProvisioningStatusUnknown        ResourceProvisioningStatus = "unknown"
)

// Error Represents a structured error response returned by the API. It consolidates both OAuth 2.0-related and general API errors into a unified format.
type Error struct {
	// Error A concise, machine-readable identifier for the specific error, enabling clients to handle particular conditions programmatically.
	Error ErrorError `json:"error"`

	// ErrorDescription A human-readable explanation that provides additional context about the error. This field is omitted when no extra description is available.
	ErrorDescription string `json:"error_description"`

	// Status The HTTP status code returned with the response.
	Status int `json:"status"`

	// TraceId A unique identifier associated with the request, allowing the issue to be traced across internal systems. Clients can provide this value when contacting support to assist with debugging.
	TraceId string `json:"trace_id"`

	// Type Specifies whether the error originated from an OAuth 2.0 context or from the general API.
	Type ErrorType `json:"type"`
}

// ErrorError A concise, machine-readable identifier for the specific error, enabling clients to handle particular conditions programmatically.
type ErrorError string

// ErrorType Specifies whether the error originated from an OAuth 2.0 context or from the general API.
type ErrorType string

// KubernetesLabelValue A valid Kubernetes label value, typically used for resource names that can be
// indexed in the database.
type KubernetesLabelValue = string

// OrganizationScopedResourceReadMetadata defines model for organizationScopedResourceReadMetadata.
type OrganizationScopedResourceReadMetadata struct {
	// CreatedBy The user who created the resource.
	CreatedBy *string `json:"createdBy,omitempty"`

	// CreationTime The time the resource was created.
	CreationTime time.Time `json:"creationTime"`

	// DeletionTime The time the resource was deleted.
	DeletionTime *time.Time `json:"deletionTime,omitempty"`

	// Description The resource description, this optionally augments the name with more context.
	Description *string `json:"description,omitempty"`

	// HealthStatus The health state of a resource.
	HealthStatus ResourceHealthStatus `json:"healthStatus"`

	// Id The unique resource ID.
	Id string `json:"id"`

	// ModifiedBy The user who updated the resource.
	ModifiedBy *string `json:"modifiedBy,omitempty"`

	// ModifiedTime The time a resource was updated.
	ModifiedTime *time.Time `json:"modifiedTime,omitempty"`

	// Name A valid Kubernetes label value, typically used for resource names that can be
	// indexed in the database.
	Name KubernetesLabelValue `json:"name"`

	// OrganizationId The organization identifier the resource belongs to.
	OrganizationId string `json:"organizationId"`

	// ProvisioningStatus The provisioning state of a resource.
	ProvisioningStatus ResourceProvisioningStatus `json:"provisioningStatus"`

	// Tags A list of tags.
	Tags *TagList `json:"tags,omitempty"`
}

// ProjectScopedResourceReadMetadata defines model for projectScopedResourceReadMetadata.
type ProjectScopedResourceReadMetadata struct {
	// CreatedBy The user who created the resource.
	CreatedBy *string `json:"createdBy,omitempty"`

	// CreationTime The time the resource was created.
	CreationTime time.Time `json:"creationTime"`

	// DeletionTime The time the resource was deleted.
	DeletionTime *time.Time `json:"deletionTime,omitempty"`

	// Description The resource description, this optionally augments the name with more context.
	Description *string `json:"description,omitempty"`

	// HealthStatus The health state of a resource.
	HealthStatus ResourceHealthStatus `json:"healthStatus"`

	// Id The unique resource ID.
	Id string `json:"id"`

	// ModifiedBy The user who updated the resource.
	ModifiedBy *string `json:"modifiedBy,omitempty"`

	// ModifiedTime The time a resource was updated.
	ModifiedTime *time.Time `json:"modifiedTime,omitempty"`

	// Name A valid Kubernetes label value, typically used for resource names that can be
	// indexed in the database.
	Name KubernetesLabelValue `json:"name"`

	// OrganizationId The organization identifier the resource belongs to.
	OrganizationId string `json:"organizationId"`

	// ProjectId The project identifier the resource belongs to.
	ProjectId string `json:"projectId"`

	// ProvisioningStatus The provisioning state of a resource.
	ProvisioningStatus ResourceProvisioningStatus `json:"provisioningStatus"`

	// Tags A list of tags.
	Tags *TagList `json:"tags,omitempty"`
}

// ResourceHealthStatus The health state of a resource.
type ResourceHealthStatus string

// ResourceMetadata Metadata required for all API resource reads and writes.
type ResourceMetadata struct {
	// Description The resource description, this optionally augments the name with more context.
	Description *string `json:"description,omitempty"`

	// Name A valid Kubernetes label value, typically used for resource names that can be
	// indexed in the database.
	Name KubernetesLabelValue `json:"name"`

	// Tags A list of tags.
	Tags *TagList `json:"tags,omitempty"`
}

// ResourceProvisioningStatus The provisioning state of a resource.
type ResourceProvisioningStatus string

// ResourceReadMetadata defines model for resourceReadMetadata.
type ResourceReadMetadata struct {
	// CreatedBy The user who created the resource.
	CreatedBy *string `json:"createdBy,omitempty"`

	// CreationTime The time the resource was created.
	CreationTime time.Time `json:"creationTime"`

	// DeletionTime The time the resource was deleted.
	DeletionTime *time.Time `json:"deletionTime,omitempty"`

	// Description The resource description, this optionally augments the name with more context.
	Description *string `json:"description,omitempty"`

	// HealthStatus The health state of a resource.
	HealthStatus ResourceHealthStatus `json:"healthStatus"`

	// Id The unique resource ID.
	Id string `json:"id"`

	// ModifiedBy The user who updated the resource.
	ModifiedBy *string `json:"modifiedBy,omitempty"`

	// ModifiedTime The time a resource was updated.
	ModifiedTime *time.Time `json:"modifiedTime,omitempty"`

	// Name A valid Kubernetes label value, typically used for resource names that can be
	// indexed in the database.
	Name KubernetesLabelValue `json:"name"`

	// ProvisioningStatus The provisioning state of a resource.
	ProvisioningStatus ResourceProvisioningStatus `json:"provisioningStatus"`

	// Tags A list of tags.
	Tags *TagList `json:"tags,omitempty"`
}

// ResourceWriteMetadata Metadata required for all API resource reads and writes.
type ResourceWriteMetadata = ResourceMetadata

// Semver A semantic version in the form v1.2.3.
// Pre-releases and variants are not currently supported.
type Semver = string

// StaticResourceMetadata defines model for staticResourceMetadata.
type StaticResourceMetadata struct {
	// CreatedBy The user who created the resource.
	CreatedBy *string `json:"createdBy,omitempty"`

	// CreationTime The time the resource was created.
	CreationTime time.Time `json:"creationTime"`

	// Description The resource description, this optionally augments the name with more context.
	Description *string `json:"description,omitempty"`

	// Id The unique resource ID.
	Id string `json:"id"`

	// ModifiedBy The user who updated the resource.
	ModifiedBy *string `json:"modifiedBy,omitempty"`

	// ModifiedTime The time a resource was updated.
	ModifiedTime *time.Time `json:"modifiedTime,omitempty"`

	// Name A valid Kubernetes label value, typically used for resource names that can be
	// indexed in the database.
	Name KubernetesLabelValue `json:"name"`

	// Tags A list of tags.
	Tags *TagList `json:"tags,omitempty"`
}

// Tag A tag mapping arbitrary names to values.  These have no special meaning
// for any component are are intended for use by end users to add additional
// context to a resource, for example to categorize it.
type Tag struct {
	// Name A unique tag name.
	Name string `json:"name"`

	// Value The value of the tag.
	Value string `json:"value"`
}

// TagList A list of tags.
type TagList = []Tag

// TagSelectorParameter defines model for tagSelectorParameter.
type TagSelectorParameter = []string

// BadRequestResponse Represents a structured error response returned by the API. It consolidates both OAuth 2.0-related and general API errors into a unified format.
type BadRequestResponse = Error

// ConflictResponse Represents a structured error response returned by the API. It consolidates both OAuth 2.0-related and general API errors into a unified format.
type ConflictResponse = Error

// ForbiddenResponse Represents a structured error response returned by the API. It consolidates both OAuth 2.0-related and general API errors into a unified format.
type ForbiddenResponse = Error

// InternalServerErrorResponse Represents a structured error response returned by the API. It consolidates both OAuth 2.0-related and general API errors into a unified format.
type InternalServerErrorResponse = Error

// NotFoundResponse Represents a structured error response returned by the API. It consolidates both OAuth 2.0-related and general API errors into a unified format.
type NotFoundResponse = Error

// UnauthorizedResponse Represents a structured error response returned by the API. It consolidates both OAuth 2.0-related and general API errors into a unified format.
type UnauthorizedResponse = Error
