{{- if (and .Values.ca .Values.ca.enabled .Values.ca.generate) }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: unikorn-self-signed-issuer
  namespace: {{ .Values.certManager.namespace }}
  labels:
    {{- include "unikorn.labels" . | nindent 4 }}
spec:
  selfSigned: {}
{{- end }}
