{{- if (and .Values.ca .Values.ca.enabled (not .Values.ca.generate)) }}
apiVersion: v1
kind: Secret
metadata:
  name: unikorn-ca
  namespace: {{ .Values.certManager.namespace }}
  labels:
    {{- include "unikorn.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.ca.certificate }}
  tls.key: {{ .Values.ca.privateKey }}
{{- end }}
